"""
Veritas-Graph: Central System State & Telemetry Schemas
Enforces strict immutability and provenance tracking.
"""

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ExecutionStatus(str, Enum):
    """Enumeration for the execution status of a clause."""

    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    RETRYING = "RETRYING"
    ESCALATED_HUMAN_REVIEW = "ESCALATED_HUMAN_REVIEW"
    FAILED = "FAILED"


class BoundingBox(BaseModel):
    """Physical coordinate provenance from Phase 1.

    Attributes:
        page_number: The document page number.
        x0: Left bounding coordinate.
        top: Top bounding coordinate.
        x1: Right bounding coordinate.
        bottom: Bottom bounding coordinate.
    """

    model_config = ConfigDict(frozen=True)

    page_number: int
    x0: float
    top: float
    x1: float
    bottom: float


class ExtractedClause(BaseModel):
    """Semantic clause with physical grounding and retry state.

    Attributes:
        clause_id: Unique identifier for the clause.
        text: The raw extracted text.
        context_before: Text immediately preceding this clause for alignment context.
        redline_suggestion: Suggested replacement text from the LLM.
        section_header: The section header if identified.
        bounding_boxes: List of physical coordinates for the clause text.
        confidence_score: LLM's confidence score for the extraction/redline.
        retry_count: Number of times this clause has been retried.
        status: The current execution status.
        requires_human_review: Flag indicating if a human must review this clause.
        escalation_reason: Description of why the clause was escalated.
    """

    model_config = ConfigDict(frozen=True)

    clause_id: str
    text: str
    context_before: str = ""
    redline_suggestion: str | None = None
    section_header: str | None = None
    bounding_boxes: list[BoundingBox] = Field(default_factory=list)
    confidence_score: float = 1.0
    retry_count: int = 0
    status: ExecutionStatus = ExecutionStatus.PENDING
    requires_human_review: bool = False
    escalation_reason: str | None = None


class RedlineAction(BaseModel):
    """Native Word AST redline instruction.

    Attributes:
        clause_id: The ID of the clause being modified.
        target_paragraph_index: The matched paragraph index in the DOCX file.
        original_text: The original text to be deleted.
        replacement_text: The new text to be inserted.
        author: The metadata author of the Tracked Change.
        timestamp: The timestamp of the modification.
        is_fallback_comment: Flag if we could not inject AST and fell back to a DOCX comment.
        warning_comment: Optional warning message inserted into the document.
    """

    model_config = ConfigDict(frozen=True)

    clause_id: str
    target_paragraph_index: int | None = None
    original_text: str
    replacement_text: str
    author: str = "Veritas-AI"
    timestamp: str = ""
    is_fallback_comment: bool = False
    warning_comment: str | None = None


class TokenUsage(BaseModel):
    """Telemetry data tracking LLM token usage."""

    model_config = ConfigDict(frozen=True)

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    estimated_cost_usd: float = 0.0


class SystemState(BaseModel):
    """Immutable State Graph payload.

    All transitions must execute via state.model_copy(update={...}).

    Attributes:
        document_id: A unique ID for the document processing run.
        raw_pdf_path: Optional path to the PDF source.
        raw_docx_path: Optional path to the DOCX source.
        is_pdf_only: True if only PDF processing is required.
        chunks: List of text chunks generated by the chunker.
        unstructured_document_flag: True if document lacked expected structure.
        extracted_clauses: List of processed clauses returned by the LLM.
        redlines: List of generated AST actions ready for injection.
        node_latency_ms: Dictionary mapping node names to their execution latency in ms.
        token_telemetry: Tracked token usage for this run.
        failed_chunks: Raw data of chunks that failed processing entirely.
        requires_global_human_review: True if any clause escalated to human review.
    """

    model_config = ConfigDict(frozen=True)

    document_id: str
    raw_pdf_path: str | None = None
    raw_docx_path: str | None = None
    is_pdf_only: bool = False

    # Processing state
    chunks: list[str] = Field(default_factory=list)
    unstructured_document_flag: bool = False
    extracted_clauses: list[ExtractedClause] = Field(default_factory=list)
    redlines: list[RedlineAction] = Field(default_factory=list)

    # Telemetry & Observability
    node_latency_ms: dict[str, float] = Field(default_factory=dict)
    token_telemetry: TokenUsage = Field(default_factory=TokenUsage)
    failed_chunks: list[dict[str, Any]] = Field(default_factory=list)
    requires_global_human_review: bool = False
